name: Build and Deploy Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Build Docker image
      run: docker build -t hello-app:latest .
    
    - name: Test Docker image
      run: docker run --rm hello-app:latest nginx -t
